[logging]
logging_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/logs"

[vtt_to_txt]
input_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/vtt_to_txt/_input"
output_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/vtt_to_txt/_output"

[ner_workflow]
input_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/ner_workflow/_input"
output_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/ner_workflow/_output" 
ner_batch_size = 15
ner_threshold = 0.7
llm_max_new_tokens = 10000

[vtt_anonymization]
input_directory_vtt = "/Users/ahenderson/Documents/Whisper_Test_Files/vtt_anonymization/_input_vtt"
input_directory_json = "/Users/ahenderson/Documents/Whisper_Test_Files/vtt_anonymization/_input_json"
output_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/vtt_anonymization/_output/"

vtt_replacements = [
  { pattern = "_", replacement = "" },
  { pattern = "„", replacement = "" },
  { pattern = "“", replacement = "" },
  { pattern = "\"", replacement = "" },
  { pattern = "\\<i\\>", replacement = "" },
  { pattern = "(?:.*\\n){3}.*\\(\\.\\.\\.\\?\\).*", replacement = "" },
  { pattern = "\\(", replacement = "" },
  { pattern = "\\?\\)", replacement = "" },
  { pattern = "\\n{3,}", replacement = "\\n\\n" },
  { pattern = "(?:.*\\n){0,3}.*\\bXXX\\b.*\\n?", replacement = "" },
  { pattern = "(?:.*\\n){0,3}.*<.*\\n?", replacement = "" },
  { pattern = "> (?=[a-zA-Z])", replacement = "" }
]

[dataset_creator]
input_directory_vtt = "/Users/ahenderson/Documents/Whisper_Test_Files/_input_vtt"
input_directory_wav = "/Users/ahenderson/Documents/Whisper_Test_Files/_input_wav"
output_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/dataset_creator/_output/"
sample_rate = "16000"
offset = -0.075

[dataset_merger]
input_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/dataset_creator/_input/"
output_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/dataset_creator/_output/"
merged_dataset_name = "merged_dataset_example"

[hdf5_converter]
input_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/hdf-converter/_input"
output_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/hdf-converter/_output"
sample_rate = "16000"        
batch_size = "400"       
threads = "16" 
model = "openai/whisper-large-v3"
language = "german"

[dataset_test]
input_directory = "/Users/ahenderson/Documents/Whisper_Test_Files/dataset_test/_input/dataset_example/"